[package]
name = "rustdoc-types"
version = "0.58.0"
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Types for rustdoc's json output"
repository = "https://github.com/rust-lang/rustdoc-types"
include = ["Cargo.toml", "CHANGELOG.md", "README.md", "LICENSE-MIT", "LICENSE-APACHE", "src/**/*.rs"]
rust-version = "1.85.0"

[dependencies]
serde = {version="1.0.186"}
serde_derive = {version="1.0.186"}
rustc-hash = {version="2", optional=true}
rkyv = { version = "0.8", optional = true }

[features]
default = [] # TODO: Remove this next time we make a breaking release

rustc-hash = ["dep:rustc-hash"]
rkyv_0_8 = ["dep:rkyv"]

[dev-dependencies]
postcard = { version = "1", default-features = false, features = ["alloc"] }
serde_json = "1.0"
