name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master
      with:
        toolchain: 1.85.0
    - uses: taiki-e/install-action@a37010ded18ff788be4440302bd6830b1ae50d8b # v2.68.25
      with:
        tool: cargo-hack@0.6.43
    - uses: Swatinem/rust-cache@v2
    - run: cargo hack test --feature-powerset --locked
